queries = [
    "classic rock hits",
    "best hip hop tracks",
    "indie music videos",
    "best electronic music",
    "jazz music playlists",
    "pop music charts",
    "metal music bands",
    "folk music artists",
    "R&B music hits",
    "country music songs",
    "reggae music vibes",
    "blues music classics",
    "disco music nights",
    "techno music beats",
    "house music mixes",
    "trance music tracks",
    "drum and bass",
    "dubstep music",
    "ambient music",
    "chillout music",
    "dance music",
    "alternative rock",
    "grunge music",
    "punk rock music",
    "ska punk music",
    "hard rock music",
    "progressive rock",
    "symphonic rock",
    "gothic rock",
    "industrial rock",
    "psychedelic rock",
    "surf rock music",
    "garage rock music",
    "blues rock music",
    "folk rock music",
    "soft rock music",
    "arena rock music",
    "art rock music",
    "glam rock music",
    "heavy metal music",
    "thrash metal music",
    "death metal music",
    "black metal music",
    "power metal music",
    "doom metal music",
    "gothic metal music",
    "symphonic metal",
    "folk metal music",
    "viking metal music",
    "pagan metal music",
    "metalcore music",
    "deathcore music",
    "djent music",
    "mathcore music",
    "grindcore music",
    "electronicore music",
    "emo music",
    "post-hardcore music",
    "hardcore punk music",
    "screamo music",
    "post-rock music",
    "instrumental rock",
    "lo-fi music",
    "indie pop music",
    "dream pop music",
    "shoegaze music",
    "twee pop music",
    "chamber pop music",
    "baroque pop music",
    "psychedelic pop",
    "jangle pop music",
    "power pop music",
    "synth-pop music",
    "electro pop music",
    "dance-pop music",
    "pop-punk music",
    "emo pop music",
    "hyperpop music",
    "vaporwave music",
    "witch house music",
    "chillwave music",
    "indie electronic",
    "indietronica music",
    "electro house music",
    "progressive house",
    "deep house music",
    "tech house music",
    "acid house music",
    "tropical house",
    "future house music",
    "bass house music",
    "big room house",
    "melodic house",
    "organic house",
    "afro house music",
    "latin house music",
    "jazz house music",
    "soulful house",
    "funky house music",
    "tribal house music",
    "vocal house music",
    "acid jazz music",
    "nu jazz music",
    "smooth jazz music",
    "contemporary jazz",
    "free jazz music",
    "avant-garde jazz",
    "bebop jazz music",
    "cool jazz music",
    "hard bop jazz",
    "latin jazz music",
    "mainstream jazz",
    "modal jazz music",
    "post-bop jazz",
    "soul jazz music",
    "swing jazz music",
    "trad jazz music",
    "third stream jazz",
    "vocal jazz music",
    "west coast jazz",
    "afrobeat music",
    "highlife music",
    "juju music",
    "fuji music",
    "apala music",
    "sokomusic",
    "mbalax music",
    "raï music",
    "zouk music",
    "kompa music",
    "cadence music",
    "calypso music",
    "soca music",
    "reggaeton music",
    "bachata music",
    "salsa music",
    "merengue music",
    "tango music",
    "rumba music",
    "flamenco music",
    "fado music",
    "portuguese folk",
    "spanish folk music",
    "italian folk music",
    "german folk music",
    "irish folk music",
    "scottish folk music",
    "english folk music",
    "american folk music",
    "bluegrass music",
    "appalachian folk",
    "cajun music",
    "zydeco music",
    "gospel music",
    "christian music",
    "worship music",
    "hymns music",
    "choral music",
    "classical music",
    "baroque music",
    "classical period",
    "romantic music",
    "impressionist music",
    "modern classical",
    "contemporary classical",
    "orchestral music",
    "chamber music",
    "opera music",
    "ballet music",
    "film scores music",
    "video game music",
    "musical theater",
    "northern soul music",
    "southern rock music",
    "tex-mex music",
    "zydeco rock music",
    "celtic punk music",
    "pirate metal music",
    "kawaii metal music",
    "visual kei music",
    "j-core music",
    "happy hardcore music",
    "alternative country",
    "americana",
    "cowpunk",
    "gothic country",
    "roots rock",
    "australian country",
    "bakersfield sound",
    "bluegrass",
    "blue yodeling",
    "bro-country",
    "cajun",
    "canadian country",
    "christian country",
    "classic country",
    "country and irish",
    "country blues",
    "country en español",
    "country folk",
    "country pop",
    "country rap",
    "country rock",
    "cowboy pop",
    "dansband",
    "gulf and western",
    "honky tonk",
    "instrumental country",
    "lubbock sound",
    "nashville sound",
    "neotraditional country",
    "old-time",
    "outlaw country",
    "pop country",
    "progressive country",
    "regional mexican",
    "rockabilly",
    "southern rock",
    "southern soul",
    "sertanejo",
    "talking blues",
    "traditional country",
    "truck-driving country",
    "western",
    "zydeco",
    # Electronic Genres
    "ambient",
    "bass music",
    "breakbeat",
    "chill-out",
    "disco",
    "drum and bass",
    "dub",
    "electronic rock",
    "dance-rock",
    "alternative dance",
    "dance-punk",
    "electronic pop",
    "indietronica",
    "krautrock",
    "new wave",
    "post-rock",
    "space rock",
    "synth-metal",
    "synth-punk",
    "electronica",
    "folktronica",
    "livetronica",
    "nu jazz",
    "progressive electronic",
    "asian underground",
    "african electronic dance music",
    "budots",
    "changa tuki",
    "dancehall pop",
    "denpa music",
    "guaracha",
    "funk carioca",
    "merenhouse",
    "nortec",
    "rabòday",
    "rara tech",
    "russ music",
    "shamstep",
    "tecnocumbia",
    "tribal guarachero",
    "worldbeat",
    "black midi",
    "deconstructed club",
    "drone",
    "electroacoustic music",
    "glitch",
    "microsound",
    "noise music",
    "plunderphonics",
    "reductionism",
    # Jazz Genres
    "acid jazz",
    "afro-cuban jazz",
    "alt-jazz",
    "avant-garde jazz",
    "bebop",
    "big band",
    "boogie-woogie",
    "bossa nova",
    "brazilian jazz",
    "british dance band",
    "cape jazz",
    "chamber jazz",
    "continental jazz",
    "cool jazz",
    "crossover jazz",
    "dixieland",
    "ethno jazz",
    "european free jazz",
    "free funk",
    "free improvisation",
    "free jazz",
    "gypsy jazz",
    "hard bop",
    "jazz blues",
    "jazz-funk",
    "jazz fusion",
    "jazz rap",
    "jazz rock",
    "jazztronica",
    "kansas city jazz",
    "latin jazz",
    "livetronica",
    "m-base",
    "mainstream jazz",
    "modal jazz",
    "neo-bop",
    "neo-swing",
    "nu jazz",
    "orchestral jazz",
    "post-bop",
    "progressive jazz",
    "punk jazz",
    "samba-jazz",
    "shibuya-kei",
    "ska jazz",
    "smooth jazz",
    "soul jazz",
    "straight-ahead jazz",
    "stride jazz",
    "swing",
    "trad jazz",
    "third stream",
    "vocal jazz",
    "west coast jazz",
    # Latin & South American Genres
    "afro-pop",
    "axé",
    "bambuco",
    "banda",
    "bossa nova",
    "calypso",
    "candomblé",
    "cumbia",
    "danzón",
    "forró",
    "frevo",
    "guaracha",
    "joropo",
    "lambada",
    "mambo",
    "maracatu",
    "merengue",
    "norteño",
    "pachanga",
    "plena",
    "ranchera",
    "reggaeton",
    "salsa",
    "samba",
    "son",
    "tango",
    "timba",
    "trova",
    "vallenato",
    "zouk",
    # Folk Genres
    "american folk",
    "appalachian folk",
    "australian folk",
    "british folk",
    "cajun",
    "canadian folk",
    "celtic folk",
    "english folk",
    "german folk",
    "irish folk",
    "italian folk",
    "scottish folk",
    "spanish folk",
    "swedish folk",
    "traditional folk",
    "zydeco",
    # Metal Genres
    "heavy metal",
    "speed metal",
    "thrash metal",
    "power metal",
    "death metal",
    "black metal",
    "pagan metal",
    "viking metal",
    "folk metal",
    "symphonic metal",
    "gothic metal",
    "glam metal",
    "hair metal",
    "doom metal",
    "groove metal",
    "industrial metal",
    "modern metal",
    "neoclassical metal",
    "new wave of british heavy metal",
    "post metal",
    "progressive metal",
    "avantgarde metal",
    "sludge metal",
    "spazzcore",
    "stoner metal",
    "surf metal",
    "technical death metal",
    "tex-mex metal",
    "time lord rock",
    "trip-hop metal",
    "yacht rock",
    # Other Global Genres
    "afghan folk",
    "albanian folk",
    "algerian rai",
    "andean music",
    "angolan semba",
    "arabesque",
    "armenian folk",
    "assyrian folk",
    "azerbaijani mugham",
    "balkan brass",
    "baltic folk",
    "bangladeshi baul",
    "belarusian folk",
    "beninese voodoo",
    "berber music",
    "bolivian folk",
    "bosnian sevdalinka",
    "bulgarian folk",
    "burkina faso balafon",
    "burmese classical",
    "cameroonian bikutsi",
    "canadian aboriginal",
    "cape verdean morna",
    "central african music",
    "chadian sahel",
    "chilean nueva canción",
    "chinese classical",
    "colombian vallenato",
    "congolese rumba",
    "croatian dalmatian",
    "cuban son",
    "cypriot folk",
    "czech folk",
    "danish folk",
    "djiboutian balwo",
    "dominican merengue",
    "ecuadorian pasillo",
    "egyptian shaabi",
    "eritrean guaila",
    "estonian folk",
    "ethiopian azmari",
    "fijian meke",
    "finnish folk",
    "french cabaret",
    "georgian polyphonic",
    "german schlager",
    "ghanaian highlife",
    "greek rebetiko",
    "guatemalan marimba",
    "guinean djembe",
    "haitian kompa",
    "hungarian csárdás",
    "icelandic folk",
    "indian classical",
    "indonesian gamelan",
    "iranian dastgah",
    "iraqi maqam",
    "irish sean-nós",
    "israeli mizrahi",
    "italian tarantella",
    "jamaican mento",
    "japanese enka",
    "jordanian dabke",
    "kazakhstani kui",
    "kenyan benga",
    "kirghiz komuz",
    "kosovo albanian",
    "kuwaiti sawt",
    "kyrgyzstani kui",
    "laotian mor lam",
    "latvian dainas",
    "lebanese dabke",
    "lesotho mokorotlo",
    "liberian gbema",
    "libyan chaabi",
    "lithuanian dainos",
    "luxembourgish folk",
    "macedonian folk",
    "madagascan salegy",
    "malagasy kabosy",
    "malawian banjo",
    "malaysian joget",
    "maldivian bodu beru",
    "malian jeli",
    "maltese għana",
    "marshall islands stick dance",
    "mauritanian griot",
    "mauritian sega",
    "mexican mariachi",
    "micronesian stick dance",
    "moldovan folk",
    "mongolian morin khuur",
    "montenegrin folk",
    "moroccan gnawa",
    "mozambican marrabenta",
    "myanmar hsaing waing",
    "namibian kwela",
    "nepalese dohori",
    "nigerien Hausa",
    "nigerian fuji",
    "niuean tamakautoga",
    "north korean revolutionary",
    "norwegian bygdedans",
    "omani liwa",
    "pakistani qawwali",
    "palauan basing",
    "palestinian dabke",
    "panamanian tamborito",
    "papua new guinean sing-sing",
    "paraguayan polka",
    "peruvian marinera",
    "philippine tinikling",
    "polish polka",
    "portuguese fado",
    "qatari ardha",
    "romanian doina",
    "russian balalaika",
    "rwandan inanga",
    "sahrawi hawl",
    "samoa siva",
    "saudi khaleeji",
    "senegalese mbalax",
    "serbian kolo",
    "seychelles sega",
    "sierra leonean gumbe",
    "singaporean xinyao",
    "slovak folk",
    "slovenian polka",
    "solomon islands panpipe",
    "somali buraanbur",
    "south african isicathamiya",
    "south korean pansori",
    "south sudanese apiti",
    "spanish flamenco",
    "sri lankan baila",
    "sudanese haqiba",
    "surinamese kaseko",
    "swazi indlamu",
    "swedish polska",
    "swiss yodeling",
    "syrian muwal",
    "tajik shashmaqom",
    "tanzanian bongo flava",
    "thai mor lam",
    "timorese tebe",
    "togo atsina",
    "tongan meʻetuʻupaki",
    "trinidadian calypso",
    "tunisian malouf",
    "turkish makam",
    "turkmenistan kui",
    "tuvaluan fatele",
    "ugandan kadongo kamu",
    "ukrainian kobzar",
    "uruguayan tango",
    "uzbek shashmaqom",
    "vanuatu string band",
    "venezuelan joropo",
    "vietnamese ca trù",
    "yemeni sanʿa",
    "zambian kalindula",
    "zimbabwean mbira",
]
